config/routes.rb
Reuse::Application.routes.draw do
  resources :mlps

  resources :redes do
    member do
      get 'valida'
    end
  end

  resources :validacoes

  resources :treinamentos do
    collection do 
      get 'chama_treinamento'
      get 'treina'
    end
  end

  resources :receita

  resources :cook_books

  root :to => 'cook_books#index'

end

app/models/rede.rb
class Rede < ActiveRecord::Base
	attr_accessible :epocas, :peso1, :peso2, :peso3, :peso4, :peso5
  
	def pesos
		p = Array.new
		p.push(peso1, peso2, peso3, peso4, peso5)
		return p
	end


	def treina treinamentos

		parada = 60.times.map { 0 }
		pesos = Array.new
		pesos = 5.times.map { rand().round(2) }
		alfa = 0.0025 
		epoca = 0

		while parada.include?(0)
		  treinamentos.each_with_index do |treinamento, i|
		    parada, pesos = calcula_peso i, treinamento.entradas, pesos, treinamento.target, parada, alfa
		  end
		  epoca+=1
		end
		self.epocas = epoca
		self.peso1 = pesos[0]
		self.peso2 = pesos[1]
		self.peso3 = pesos[2]
		self.peso4 = pesos[3]
		self.peso5 = pesos[4]
		self.save


	end

	def valida validacoes
	  	total = validacoes.count
	  	certas = 0
	  	validacoes.each_with_index do |validacao|
		    saida = calcula_saida validacao.entradas
		    certas += saida == validacao.target ? 1 : 0
		end
		return total, certas
	end


private
	def calcula_saida entradas, pesos=pesos
		somatorio = 0
		entradas.each_with_index do |x, index|
		    somatorio += x*pesos[index]      
		end
		saida = somatorio >= 0 ? 1 : -1		
	end		


	def calcula_peso i, entradas, pesos, target, parada, alfa
	
	  saida = calcula_saida entradas, pesos

	  parada[i] =
	      if saida == target
	           1
	      else
	          entradas.each_with_index do |x, index|
	              pesos[index] += alfa*x*target
	          end     
	          0
	      end
	    
	  return parada, pesos
	end

end

app/controllers/redes_controller.rb
class RedesController < ApplicationController
  # GET /redes
  # GET /redes.json
  def index
    @redes = Rede.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @redes }
    end
  end

  # GET /redes/1
  # GET /redes/1.json
  def show
    @rede = Rede.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rede }
    end
  end

  def valida
    @rede = Rede.find(params[:id])
    validacoes = Validacao.all
    @total, @certas = @rede.valida validacoes
    @porcentagem_correta = ((@certas.to_f/@total)*100).to_i
    @porcentagem_errada = (((@total-@certas).to_f/@total)*100).to_i
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rede }
    end
  end
  # GET /redes/new
  # GET /redes/new.json
  def new
    @rede = Rede.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rede }
    end
  end

  # GET /redes/1/edit
  def edit
    @rede = Rede.find(params[:id])
  end

  # POST /redes
  # POST /redes.json
  def create
    @rede = Rede.new(params[:rede])

    respond_to do |format|
      if @rede.save
        format.html { redirect_to @rede, notice: 'Rede was successfully created.' }
        format.json { render json: @rede, status: :created, location: @rede }
      else
        format.html { render action: "new" }
        format.json { render json: @rede.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /redes/1
  # PUT /redes/1.json
  def update
    @rede = Rede.find(params[:id])

    respond_to do |format|
      if @rede.update_attributes(params[:rede])
        format.html { redirect_to @rede, notice: 'Rede was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rede.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redes/1
  # DELETE /redes/1.json
  def destroy
    @rede = Rede.find(params[:id])
    @rede.destroy

    respond_to do |format|
      format.html { redirect_to redes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/redes_helper.rb
module RedesHelper
end

app/views/redes/_form.html.erb
<%= form_for(@rede) do |f| %>
  <% if @rede.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rede.errors.count, "error") %> prohibited this rede from being saved:</h2>

      <ul>
      <% @rede.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :peso1 %><br />
    <%= f.text_field :peso1 %>
  </div>
  <div class="field">
    <%= f.label :peso2 %><br />
    <%= f.text_field :peso2 %>
  </div>
  <div class="field">
    <%= f.label :peso3 %><br />
    <%= f.text_field :peso3 %>
  </div>
  <div class="field">
    <%= f.label :peso4 %><br />
    <%= f.text_field :peso4 %>
  </div>
  <div class="field">
    <%= f.label :peso5 %><br />
    <%= f.text_field :peso5 %>
  </div>
  <div class="field">
    <%= f.label :epocas %><br />
    <%= f.number_field :epocas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/redes/edit.html.erb
<h1>Editing rede</h1>

<%= render 'form' %>

<%= link_to 'Show', @rede %> |
<%= link_to 'Back', redes_path %>

app/views/redes/index.html.erb
<h1>Listing redes</h1>

<table>
  <tr>
    <th>Peso1</th>
    <th>Peso2</th>
    <th>Peso3</th>
    <th>Peso4</th>
    <th>Peso5</th>
    <th>Epocas</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @redes.each do |rede| %>
  <tr>
    <td><%= rede.peso1 %></td>
    <td><%= rede.peso2 %></td>
    <td><%= rede.peso3 %></td>
    <td><%= rede.peso4 %></td>
    <td><%= rede.peso5 %></td>
    <td><%= rede.epocas %></td>
    <td><%= link_to 'Show', rede %></td>
    <td><%= link_to 'Valida rede', valida_rede_path(rede) %></td>
    <td><%= link_to 'Edit', edit_rede_path(rede) %></td>
    <td><%= link_to 'Destroy', rede, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rede', new_rede_path %>

app/views/redes/new.html.erb
<h1>New rede</h1>

<%= render 'form' %>

<%= link_to 'Back', redes_path %>

app/views/redes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Peso1:</b>
  <%= @rede.peso1 %>
</p>

<p>
  <b>Peso2:</b>
  <%= @rede.peso2 %>
</p>

<p>
  <b>Peso3:</b>
  <%= @rede.peso3 %>
</p>

<p>
  <b>Peso4:</b>
  <%= @rede.peso4 %>
</p>

<p>
  <b>Peso5:</b>
  <%= @rede.peso5 %>
</p>

<p>
  <b>Epocas:</b>
  <%= @rede.epocas %>
</p>


<%= link_to 'Edit', edit_rede_path(@rede) %> |
<%= link_to 'Back', redes_path %>

app/views/redes/valida.html.erb
número de dados para validacao da rede:<b> <%= @total %></b>
<br/>
número de dados corretos:<b> <%= @certas %></b>
<br/>
porcentagem de acerto da rede: <b><%= @porcentagem_correta %>%</b>
<br/>
porcentagem de erro da rede: <b><%= @porcentagem_errada %>%</b>
<br/>
<%= link_to 'Show', @rede %>
<%= link_to 'Back', redes_path %>