config/routes.rb
Reuse::Application.routes.draw do
  resources :mlps

  resources :redes do
    member do
      get 'valida'
    end
  end

  resources :validacoes

  resources :treinamentos do
    collection do 
      get 'chama_treinamento'
      get 'treina'
    end
  end

  resources :receita

  resources :cook_books

  root :to => 'cook_books#index'

end

app/models/treinamento.rb
class Treinamento < ActiveRecord::Base
  attr_accessible :entrada1, :entrada2, :entrada3, :entrada4, :entrada5, :target




	def entradas
		a = Array.new
		a.push(entrada1, entrada2, entrada3, entrada4, entrada5)
		return a
	end


  def treina_rede
  	parada = 60.times.map { 0 }
	pesos = Array.new
	pesos = 5.times.map { rand().round(2) }
	alfa = 0.0025	
	epoca = 0
	
	while parada.include?(0)
	    60.times do |i|
	    	parada, pesos = calcula_peso i, x[i], pesos, target[i], parada, alfa
	    end
	    epoca+=1
	end

	return pesos, epoca
  	
  end



	def calcula_peso i, entradas,pesos, target, parada, alfa
	    somatorio = 0
	    entradas.each_with_index do |x, index|
	        somatorio += x*pesos[index]      
	    end
	    saida = somatorio >= 0 ? 1 : -1
	    parada[i] =
	        if saida == target
	             1
	        else
	            entradas.each_with_index do |x, index|
	                pesos[index] += alfa*x*target
	            end     
	            0
	        end
	      
	    return parada, pesos

	end











end

app/controllers/treinamentos_controller.rb
class TreinamentosController < ApplicationController
  # GET /treinamentos
  # GET /treinamentos.json
  def index
    @treinamentos = Treinamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @treinamentos }
    end
  end

  # GET /treinamentos/1
  # GET /treinamentos/1.json
  def show
    @treinamento = Treinamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @treinamento }
    end
  end
  
  def chama_treinamento
    rede = Rede.new
    treinamentos = Treinamento.all
    rede.treina treinamentos
    @rede = rede
    respond_to do |format|
      format.html # treina.html.erb
      format.json { render json: @pesos }
    end
  end

  def treina
    parada = 60.times.map { 0 }
    pesos = Array.new
    pesos = 5.times.map { rand().round(2) }
    alfa = 0.0025 
    epoca = 0
    treinamentos = Treinamento.all
   
    while parada.include?(0)
      treinamentos.each_with_index do |treinamento, i|
        parada, pesos = calcula_peso i, treinamento.entradas, pesos, treinamento.target, parada, alfa
      end
      epoca+=1
    end
    @epocas = epoca
    @pesos = pesos
    respond_to do |format|
      format.html # treina.html.erb
      format.json { render json: @pesos }
    end
  end

  def calcula_peso i, entradas, pesos, target, parada, alfa
      somatorio = 0
      entradas.each_with_index do |x, index|
          somatorio += x*pesos[index]      
      end
      saida = somatorio >= 0 ? 1 : -1
      parada[i] =
          if saida == target
               1
          else
              entradas.each_with_index do |x, index|
                  pesos[index] += alfa*x*target
              end     
              0
          end
        
      return parada, pesos

  end

  # GET /treinamentos/new
  # GET /treinamentos/new.json
  def new
    @treinamento = Treinamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @treinamento }
    end
  end

  # GET /treinamentos/1/edit
  def edit
    @treinamento = Treinamento.find(params[:id])
  end

  # POST /treinamentos
  # POST /treinamentos.json
  def create
    @treinamento = Treinamento.new(params[:treinamento])

    respond_to do |format|
      if @treinamento.save
        format.html { redirect_to @treinamento, notice: 'Treinamento was successfully created.' }
        format.json { render json: @treinamento, status: :created, location: @treinamento }
      else
        format.html { render action: "new" }
        format.json { render json: @treinamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /treinamentos/1
  # PUT /treinamentos/1.json
  def update
    @treinamento = Treinamento.find(params[:id])

    respond_to do |format|
      if @treinamento.update_attributes(params[:treinamento])
        format.html { redirect_to @treinamento, notice: 'Treinamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @treinamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treinamentos/1
  # DELETE /treinamentos/1.json
  def destroy
    @treinamento = Treinamento.find(params[:id])
    @treinamento.destroy

    respond_to do |format|
      format.html { redirect_to treinamentos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/treinamentos_helper.rb
module TreinamentosHelper
end

app/views/treinamentos/_form.html.erb
<%= form_for(@treinamento) do |f| %>
  <% if @treinamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@treinamento.errors.count, "error") %> prohibited this treinamento from being saved:</h2>

      <ul>
      <% @treinamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entrada1 %><br />
    <%= f.text_field :entrada1 %>
  </div>
  <div class="field">
    <%= f.label :entrada2 %><br />
    <%= f.text_field :entrada2 %>
  </div>
  <div class="field">
    <%= f.label :entrada3 %><br />
    <%= f.text_field :entrada3 %>
  </div>
  <div class="field">
    <%= f.label :entrada4 %><br />
    <%= f.text_field :entrada4 %>
  </div>
  <div class="field">
    <%= f.label :entrada5 %><br />
    <%= f.text_field :entrada5 %>
  </div>
  <div class="field">
    <%= f.label :target %><br />
    <%= f.text_field :target %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/treinamentos/chama_treinamento.html.erb
pesos resultantes do treinamento:  <b><%= @rede.pesos %></b>
<br/>
número de épocas necessárias para treinar: <b><%= @rede.epocas %></b>
<br/>
<td><%= link_to 'Mostrar rede', @rede %></td>
<td><%= link_to 'Validar rede', valida_rede_path(@rede) %></td>

app/views/treinamentos/edit.html.erb
<h1>Editing treinamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @treinamento %> |
<%= link_to 'Back', treinamentos_path %>

app/views/treinamentos/index.html.erb
<h1>Listing treinamentos</h1>

<table>
  <tr>
    <th>Entrada1</th>
    <th>Entrada2</th>
    <th>Entrada3</th>
    <th>Entrada4</th>
    <th>Entrada5</th>
    <th>Target</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @treinamentos.each do |treinamento| %>
  <tr>
    <td><%= treinamento.entrada1 %></td>
    <td><%= treinamento.entrada2 %></td>
    <td><%= treinamento.entrada3 %></td>
    <td><%= treinamento.entrada4 %></td>
    <td><%= treinamento.entrada5 %></td>
    <td><%= treinamento.target %></td>
    <td><%= link_to 'Show', treinamento %></td>
    <td><%= link_to 'Edit', edit_treinamento_path(treinamento) %></td>
    <td><%= link_to 'Destroy', treinamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Treinamento', new_treinamento_path %>
<%= link_to 'Treinar nova rede', chama_treinamento_treinamentos_path %>

app/views/treinamentos/new.html.erb
<h1>New treinamento</h1>

<%= render 'form' %>

<%= link_to 'Back', treinamentos_path %>

app/views/treinamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Entrada1:</b>
  <%= @treinamento.entrada1 %>
</p>

<p>
  <b>Entrada2:</b>
  <%= @treinamento.entrada2 %>
</p>

<p>
  <b>Entrada3:</b>
  <%= @treinamento.entrada3 %>
</p>

<p>
  <b>Entrada4:</b>
  <%= @treinamento.entrada4 %>
</p>

<p>
  <b>Entrada5:</b>
  <%= @treinamento.entrada5 %>
</p>

<p>
  <b>Target:</b>
  <%= @treinamento.target %>
</p>


<%= link_to 'Edit', edit_treinamento_path(@treinamento) %> |
<%= link_to 'Back', treinamentos_path %>

app/views/treinamentos/treina.html.erb
  <%= @pesos.inspect %>
  <br/>
  <%= @epocas %>