config/routes.rb
Reuse::Application.routes.draw do
  resources :mlps

  resources :redes do
    member do
      get 'valida'
    end
  end

  resources :validacoes

  resources :treinamentos do
    collection do 
      get 'chama_treinamento'
      get 'treina'
    end
  end

  resources :receita

  resources :cook_books

  root :to => 'cook_books#index'

end

app/controllers/validacoes_controller.rb
class ValidacoesController < ApplicationController
  # GET /validacoes
  # GET /validacoes.json
  def index
    @validacoes = Validacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @validacoes }
    end
  end

  # GET /validacoes/1
  # GET /validacoes/1.json
  def show
    @validacao = Validacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @validacao }
    end
  end

  # GET /validacoes/new
  # GET /validacoes/new.json
  def new
    @validacao = Validacao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @validacao }
    end
  end

  # GET /validacoes/1/edit
  def edit
    @validacao = Validacao.find(params[:id])
  end

  # POST /validacoes
  # POST /validacoes.json
  def create
    @validacao = Validacao.new(params[:validacao])

    respond_to do |format|
      if @validacao.save
        format.html { redirect_to @validacao, notice: 'Validacao was successfully created.' }
        format.json { render json: @validacao, status: :created, location: @validacao }
      else
        format.html { render action: "new" }
        format.json { render json: @validacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /validacoes/1
  # PUT /validacoes/1.json
  def update
    @validacao = Validacao.find(params[:id])

    respond_to do |format|
      if @validacao.update_attributes(params[:validacao])
        format.html { redirect_to @validacao, notice: 'Validacao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @validacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /validacoes/1
  # DELETE /validacoes/1.json
  def destroy
    @validacao = Validacao.find(params[:id])
    @validacao.destroy

    respond_to do |format|
      format.html { redirect_to validacoes_url }
      format.json { head :no_content }
    end
  end
end

app/views/validacoes/_form.html.erb
<%= form_for(@validacao) do |f| %>
  <% if @validacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@validacao.errors.count, "error") %> prohibited this validacao from being saved:</h2>

      <ul>
      <% @validacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entrada1 %><br />
    <%= f.text_field :entrada1 %>
  </div>
  <div class="field">
    <%= f.label :entrada2 %><br />
    <%= f.text_field :entrada2 %>
  </div>
  <div class="field">
    <%= f.label :entrada3 %><br />
    <%= f.text_field :entrada3 %>
  </div>
  <div class="field">
    <%= f.label :entrada4 %><br />
    <%= f.text_field :entrada4 %>
  </div>
  <div class="field">
    <%= f.label :entrada5 %><br />
    <%= f.text_field :entrada5 %>
  </div>
  <div class="field">
    <%= f.label :target %><br />
    <%= f.text_field :target %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/validacoes/edit.html.erb
<h1>Editing validacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @validacao %> |
<%= link_to 'Back', validacoes_path %>

app/views/validacoes/index.html.erb
<h1>Listing validacoes</h1>

<table>
  <tr>
    <th>Entrada1</th>
    <th>Entrada2</th>
    <th>Entrada3</th>
    <th>Entrada4</th>
    <th>Entrada5</th>
    <th>Target</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @validacoes.each do |validacao| %>
  <tr>
    <td><%= validacao.entrada1 %></td>
    <td><%= validacao.entrada2 %></td>
    <td><%= validacao.entrada3 %></td>
    <td><%= validacao.entrada4 %></td>
    <td><%= validacao.entrada5 %></td>
    <td><%= validacao.target %></td>
    <td><%= link_to 'Show', validacao %></td>
    <td><%= link_to 'Edit', edit_validacao_path(validacao) %></td>
    <td><%= link_to 'Destroy', validacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Validacao', new_validacao_path %>

app/views/validacoes/new.html.erb
<h1>New validacao</h1>

<%= render 'form' %>

<%= link_to 'Back', validacoes_path %>

app/views/validacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Entrada1:</b>
  <%= @validacao.entrada1 %>
</p>

<p>
  <b>Entrada2:</b>
  <%= @validacao.entrada2 %>
</p>

<p>
  <b>Entrada3:</b>
  <%= @validacao.entrada3 %>
</p>

<p>
  <b>Entrada4:</b>
  <%= @validacao.entrada4 %>
</p>

<p>
  <b>Entrada5:</b>
  <%= @validacao.entrada5 %>
</p>

<p>
  <b>Target:</b>
  <%= @validacao.target %>
</p>


<%= link_to 'Edit', edit_validacao_path(@validacao) %> |
<%= link_to 'Back', validacoes_path %>

app/views/validacoes/valida.html.erb
<%= @total %>
<br/>
<%= @certas %>