config/routes.rb
Reuse::Application.routes.draw do
  resources :mlps

  resources :redes do
    member do
      get 'valida'
    end
  end

  resources :validacoes

  resources :treinamentos do
    collection do 
      get 'chama_treinamento'
      get 'treina'
    end
  end

  resources :receita

  resources :cook_books

  root :to => 'cook_books#index'

end

app/models/cook_book.rb
class CookBook < ActiveRecord::Base
  attr_accessible :nome, :tema
end

app/controllers/cook_books_controller.rb
class CookBooksController < ApplicationController
  # GET /cook_books
  # GET /cook_books.json
  def index
    @cook_books = CookBook.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cook_books }
    end
  end

  # GET /cook_books/1
  # GET /cook_books/1.json
  def show
    @cook_book = CookBook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cook_book }
    end
  end

  # GET /cook_books/new
  # GET /cook_books/new.json
  def new
    @cook_book = CookBook.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cook_book }
    end
  end

  # GET /cook_books/1/edit
  def edit
    @cook_book = CookBook.find(params[:id])
  end

  # POST /cook_books
  # POST /cook_books.json
  def create
    @cook_book = CookBook.new(params[:cook_book])

    respond_to do |format|
      if @cook_book.save
        format.html { redirect_to @cook_book, notice: 'Cook book was successfully created.' }
        format.json { render json: @cook_book, status: :created, location: @cook_book }
      else
        format.html { render action: "new" }
        format.json { render json: @cook_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cook_books/1
  # PUT /cook_books/1.json
  def update
    @cook_book = CookBook.find(params[:id])

    respond_to do |format|
      if @cook_book.update_attributes(params[:cook_book])
        format.html { redirect_to @cook_book, notice: 'Cook book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cook_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cook_books/1
  # DELETE /cook_books/1.json
  def destroy
    @cook_book = CookBook.find(params[:id])
    @cook_book.destroy

    respond_to do |format|
      format.html { redirect_to cook_books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cook_books_helper.rb
module CookBooksHelper
end

app/views/cook_books/_form.html.erb
<%= form_for(@cook_book) do |f| %>
  <% if @cook_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cook_book.errors.count, "error") %> prohibited this cook_book from being saved:</h2>

      <ul>
      <% @cook_book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :tema %><br />
    <%= f.text_field :tema %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cook_books/edit.html.erb
<h1>Editing cook_book</h1>

<%= render 'form' %>

<%= link_to 'Show', @cook_book %> |
<%= link_to 'Back', cook_books_path %>

app/views/cook_books/index.html.erb
<h1>Listing cook_books</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Tema</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cook_books.each do |cook_book| %>
  <tr>
    <td><%= cook_book.nome %></td>
    <td><%= cook_book.tema %></td>
    <td><%= link_to 'Show', cook_book %></td>
    <td><%= link_to 'Edit', edit_cook_book_path(cook_book) %></td>
    <td><%= link_to 'Destroy', cook_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cook book', new_cook_book_path %>

app/views/cook_books/new.html.erb
<h1>New cook_book</h1>

<%= render 'form' %>

<%= link_to 'Back', cook_books_path %>

app/views/cook_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cook_book.nome %>
</p>

<p>
  <b>Tema:</b>
  <%= @cook_book.tema %>
</p>


<%= link_to 'Edit', edit_cook_book_path(@cook_book) %> |
<%= link_to 'Back', cook_books_path %>